### ISSUE TITLE
How  visualization

### ISSUE THREAD

**Issue by Lizhijian-123** [linhaojia13/PointMetaBase#6]
Hello, I found your code and only found that vis_3d.py is related to visualization. I would like to ask you, I want to visualize gt and pred, what should I do (if possible, please be as detailed as possible, thank you very much)? I got the txt files of gt and pred were obtained during the test.

**Comment by Lizhijian-123** [comment]
Hello, there are still a few questions I would like to ask. First, why does s3dis set 24,000 points, while scannet takes 64,000 points, which leads to a huge amount of calculation for scannet. Is this obtained through experiments? Can I reduce the number of points? Secondly, why does profile.py use 15,000 points to measure throughput and calculation? Is there any reason for this? Finally, why is the accuracy of each model training unstable, and the fluctuation can be between 0.3 and 0.5 , it is difficult to observe the effect of the module you added, because its gain is just in this fluctuation range. I am very much looking forward to your reply, thank you very much.

**Comment by linhaojia13** [comment]
> Hello, I found your code and only found that vis_3d.py is related to visualization. I would like to ask you, I want to visualize gt and pred, what should I do (if possible, please be as detailed as possible, thank you very much)? I got the txt files of gt and pred were obtained during the test.

As mentioned in the Readme, this code repository is built on top of [PointNeXt](https://github.com/guochengqian/PointNeXt). While using vis3d.py, I encountered some difficulties, so I didn't use this script for visualization. Instead, my visualization method is very simple: I save the point cloud that needs to be visualized as a txt file and open it using CloudCompare.

**Comment by linhaojia13** [comment]
> Hello, there are still a few questions I would like to ask. First, why does s3dis set 24,000 points, while scannet takes 64,000 points, which leads to a huge amount of calculation for scannet. Is this obtained through experiments? Can I reduce the number of points? Secondly, why does profile.py use 15,000 points to measure throughput and calculation? Is there any reason for this? Finally, why is the accuracy of each model training unstable, and the fluctuation can be between 0.3 and 0.5 , it is difficult to observe the effect of the module you added, because its gain is just in this fluctuation range. I am very much looking forward to your reply, thank you very much.

1. Our code repository is built on top of PointNeXt, which follows the experimental protocol of previous work and uses grid sampling to preprocess point clouds. For S3DIS, the voxel size is 0.04m, while for ScanNet it is 0.02m. Therefore, it is obvious that the input for ScanNet is denser than that for S3DIS. You can adjust the specific number of points to strike a balance between efficiency and performance, but I haven't tried that myself.

2. Regarding why the point number is set to 15000 for measuring throughput, I am not sure myself. I simply follow the same experimental protocol as PointNeXt to facilitate comparison.

3. As for the issue of unstable performance, I have also been troubled by it for a long time and am happy to share my thoughts with you. It is generally recognized that evaluating model performance on S3DIS is unstable. Even with the same model and training strategies, there may be differences of over 0.5. In exploring PointMeta, I trained and evaluated the same model three times to mitigate this instability. In addition, PointMetaBase has significant improvements in both efficiency and performance compared to previous methods, surpassing the fluctuations caused by these random variables. If you find it difficult to observe improvements beyond random fluctuations while exploring your methods, you may need to consider whether your modifications are truly valuable.

**Comment by Lizhijian-123** [comment]
> 

I also do the same, but how to save it as a picture after cloudcompare is opened? Direct screenshots are not very beautiful.

**Comment by linhaojia13** [comment]
> > 
> 
> I also do the same, but how to save it as a picture after cloudcompare is opened? Direct screenshots are not very beautiful.

I just used screenshots.

**Comment by Lizhijian-123** [comment]
> 

Thank you very much for your reply. I also thought about running multiple experiments to verify the reliability of the results, but the computing power and time are not enough. Regarding the improvement of performance, I started to change one by one and then superimposed, so sometimes a small The change may be effective, but the gain is limited. It is difficult to observe. At the same time, my purpose is to publish a simple paper, so I don't hold out hope that there will be a big improvement.

**Comment by Lizhijian-123** [comment]
> > > 
> > 
> > 
> > I also do the same, but how to save it as a picture after cloudcompare is opened? Direct screenshots are not very beautiful.
> 
> I just used screenshots.

Thank you for your reply, I will try how to make screenshots more beautiful

**Comment by linhaojia13** [comment]
> > 
> 
> Thank you very much for your reply. I also thought about running multiple experiments to verify the reliability of the results, but the computing power and time are not enough. Regarding the improvement of performance, I started to change one by one and then superimposed, so sometimes a small The change may be effective, but the gain is limited. It is difficult to observe. At the same time, my purpose is to publish a simple paper, so I don't hold out hope that there will be a big improvement.

Keep it up!
